server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExists=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  application:
    name: HelloWorld
    description: A Demo for Spring Boot hello World!
    author:
      name: Homer Simpson
      bio: Nuclear Safety Inspector, Former Technical Supervisor
