server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExists=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update